---
title: "plant complexity"
author: "C. Nell"
date: "7/27/2018"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
---

```{r, include=FALSE}
knitr::opts_chunk$set(tidy=TRUE,error = TRUE, eval = TRUE, message = FALSE, warning = FALSE,cache=TRUE, rows.print=5, cols.min.print=4)
theme_set(theme_minimal())

```

```{r Load preliminary packages, include=FALSE}
library(dplyr) ## for data wrangling - %>% function
library(reshape2) ##melt and cast data
library(tidyr) # 'separate' function
library(vegan) # dissimilarity matrix, permanova functions
library(tidyverse)
library(magrittr)
# phylogenies
library(phytools)
library(ape)
library(geiger)

std <- function(x) sd(x)/sqrt(length(x))

## plot theme for regressions
css_theme<-list(theme_minimal(),
                theme(axis.line = element_line(color='black'),
                      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                      legend.position = 'none', 
                      axis.ticks = element_line(color='black'),
                      axis.title = element_text(size=9),
                      axis.text = element_text(size=9)))
```  

#### Plant phylogeny  
```{r, eval=FALSE, include=FALSE}
## S.PhyloMaker function to generate phylogeny for seed plants
source("https://raw.githubusercontent.com/jinyizju/S.PhyloMaker/master/R_codes%20for%20S.PhyloMaker")
# Citation: Qian, H. and Y. Jin. (2016) An updated megaphylogeny of plants, a tool for generating plant phylogenies and an analysis of phylogenetic community structure. Journal of Plant Ecology 9(2): 233–239.
# uses PhytoPhylo species-level megaphylogeny as a backbone (Zanne et al 2014)

phylo<-read.tree("data/trees/QianJin_2016.txt") # megaphylogeny from Qian & Jim 2016 "PhytoPhylo"
nodes<-read.table('https://raw.githubusercontent.com/jinyizju/S.PhyloMaker/master/nodes', fill=TRUE, header=TRUE)# nodes for phylogeny

sp.list<-read.csv('data/2018/css_taxa.csv')%>%
  dplyr::select(species, genus, family, code)

# artemisia species are not in megaphy, use representative taxa from subgenera for divergence
new.sp.list<-sp.list%>%
  mutate(species=ifelse(species == 'Artemisia californica', 'Artemisia tridentata', 
                        ifelse(species == 'Artemisia douglasiana', 'Artemisia ludoviciana', paste(species))))
result<-S.PhyloMaker(spList=new.sp.list, tree=phylo, nodes=nodes)# prune megaphy to species list
phy<-result$Scenario.1%>%makeLabel()

write.tree(phy, 'data/2018/css_phy_raw.tree')

#change back names
new.phy<-phy
new.phy$tip.label<-ifelse(new.phy$tip.label == 'Artemisia_tridentata', 'Artemisia_californica',
                     ifelse(new.phy$tip.label == 'Artemisia_ludoviciana', 'Artemisia_douglasiana',paste(new.phy$tip.label)))

write.tree(new.phy, 'data/2018/css_tree.tre')

new.phy.new<-drop.tip(new.phy, tip="Stipa_pulchra")
write.tree(new.phy.new, 'data/2018/css_tree_clean.tre')

```  
```{r}
## read in phylogeny
phy<-read.tree('data/2018/css_tree_clean.tre')
```

#### Data  

Use arthropod length to estimate arthropod biomass  
```{r athropod biomass, eval=FALSE, include=FALSE}
# data frame with a row for each individual arthropod, identified to order and length measured
sizes<-read.csv('data/2018/CSS_arth_size.csv')

# read in Hodar conversions
hodar<-read.csv('data/2018/hodar_biomass.csv')%>%dplyr::select(Taxa,Order,a,b)
#setdiff(sizes$Order, hodar$Order) # all orders needed exist in hodar df

##calculate biomass - Hodar Equation: W=a*BodyLength^b
sized<-sizes%>%left_join(hodar, by='Order')%>%
  mutate(biomass = (a*length^b))%>%mutate(feed=tolower(feed))

#write.csv(sized, 'data/2018/CSS_arth_biomass.csv', row.names=FALSE)
```  

Determine arthropod biomass by trophic group for each individual plant  
```{r arth density, eval=FALSE, include=FALSE}
biomass.df<-read.csv('data/2018/CSS_arth_biomass.csv')

#calculate the biomass of herb, pred, omni on each plant, IP:H
biomass.plant<-biomass.df%>%
  group_by(species, Sample, treat, feed)%>%
  summarize(mg = sum(biomass, na.rm=TRUE), abun = length(biomass))%>%
  mutate(plant_total_mg = ave(mg, Sample, FUN = sum), plant_total_abun = ave(abun, Sample, FUN = sum))%>%
  melt(id.vars=c('species','Sample','treat','feed','plant_total_mg', 'plant_total_abun'))%>%
  dcast(species+Sample+treat+plant_total_mg+plant_total_abun~feed+variable, fill=0)%>%
  mutate(iph_mg = pred_mg/herb_mg, iph_abun=pred_abun/herb_abun, 
         iph_mg_omni=pred_mg/(omni_mg+herb_mg), iph_abun_omni=pred_abun/(omni_abun+herb_abun))
biomass.plant # wide format - col for each trophic mg and abun

write.csv(biomass.plant, 'data/ms/css_arth_biomass_byplant.csv', row.names=FALSE)

## combine with complexity data
allplant<-read.csv('data/ms/css_plant_all.csv')
allplants<-allplant%>%left_join(biomass.plant, by=c('species','sample'='Sample', 'treat'))%>%
  mutate_at(vars(plant_total_mg:pred_abun), funs(dens=./plant_g)) # calculate densities
allplants

write.csv(allplants, 'data/ms/css_arth_comp.csv', row.names=FALSE)
#just need the LRR bird effect on herb_mg_dens, pred_mg_dens
```
Look at arthropod communities  
```{r}
biomass.df<-read.csv('data/2018/CSS_arth_biomass.csv')


## how does arthropod community composition & biomass differ with treatment, species, complexity?
str(biomass.df)

# make wide
mg.df<-biomass.df%>%
  dplyr::select(species, Sample, treat, Order, biomass)%>%
  group_by(species, treat, Sample, Order)%>%
  summarize(mg=sum(biomass, na.rm=TRUE))%>%
  dcast(species+treat+Sample~Order)%>%
  mutate(samp=paste0(species, treat))%>%
  dplyr::select(species, Sample, samp, treat, everything())

mg.df[is.na(mg.df)]<-0

mg.dist<-vegdist(mg.df[,-1:-4], method='bray')

mg.ad<-adonis(mg.dist~treat*species, data=mg.df, permutations=1000)
mg.ad
# composition differs with treatment and species

mg.mds<-metaMDS(mg.dist)
# does not converge


# try other
# 
mg.cap<-capscale(mg.dist~1, comm=mg.df[,-1:-3])
mg.cap<-capscale(mg.df[,-1:-4]~treat+ARAN+COLE+Condition(species), comm=mg.df[,-1:-4], data=mg.df)
head(summary(mg.cap))
```
```{r}
#str(mg.cap)
cap.sp<-data.frame(scores(mg.cap)$species)
cap.sp$sps<-rownames(cap.sp)
cap.good<-cap.sp%>%filter(sps %in% c('COLE','ARAN','HETE','HYME','THYS','AUCH'))

cap.site<-data.frame(scores(mg.cap)$centroids)#%>%cbind(mg.df[,1:3])

ggplot()+
  geom_text(data=cap.site, aes(x=CAP1, y=CAP2, label=rownames(cap.site)), size=2)+
  geom_text(data=cap.good, aes(x=CAP1, y=CAP2, label=sps))+
  theme_bw()

## need species centroids and treatment centroids - or centroids for each species * treat

str(mg.cap)
mg.cap$CCA$centroids
scores(mg.cap)
```

```{r}
cpa.env<-envfit(mg.cap, env=mg.df)
# aran auch, cole, hete, hyme, thys
# treat, sps

str(cpa.env)

str(cpa.env$factors)

cent<-data.frame(cpa.env$factors$centroids)
str(cent)
cent$fact<-rownames(cent)  
str(cent)  
centgood<-cent%>%filter(fact %in% c('speciesACRA','speciesARDO','speciesENCA','speciesERFA','speciesERPA','speciesLUAL','speciesSAAP','speciesSAME','speciesISME','treatC','treatT'))


ggplot()+
  geom_text(data=centgood, aes(x=MDS1, y=MDS2, label=fact), size=2)+
  geom_text(data=cap.good, aes(x=MDS1*.2, y=MDS2*.2, label=sps))+
  theme_bw()

## add on bird effect as relates to community comp?
mg.cap.c<-capscale(mg.df[,-1:-3]~treat*species, comm=mg.df[,-1:-3], data=mg.df)
summary(mg.cap.c)

?capscale
```

```{r sps means both treats}
# plant-level dataframe
allplants<-read.csv('data/ms/css_arth_comp.csv')

#calculate species means + se for both treatments - herb (lrr, resist), pred(lrr), IP:H, 
all.sps.treat<-allplants%>%dplyr::select(species, sample, treat,
                        omni_mg_dens, herb_mg_dens, pred_mg_dens, plant_total_mg_dens, 
                        iph_mg_omni, iph_abun_omni, iph_mg, iph_abun)%>%
  mutate(herb_omni_mg_dens = herb_mg_dens+omni_mg_dens)%>%
  melt(id.vars=c('species','sample','treat'))%>%
  group_by(species, treat, variable)%>%
  summarize(mean=mean(value, na.rm=TRUE), se=se(value), sd=sd(value, na.rm=TRUE), n=length(value))%>%
  melt(id.vars=c('species','treat','variable'), variable.name='metric')%>%
  dcast(species+variable~treat+metric)
all.sps.treat

write.csv(all.sps.treat, 'data/ms/css_treat_means.csv', row.names=FALSE)

```  

Measure the effect of bird predators as the log response ratio  
```{r calc lrr bird}
##LRR bird effect 
# group1 = control .... so if negative means that birds reduced 
library(metafor)

lrr.all<-summary(escalc('ROM', m1i=C_mean, m2i = T_mean, sd1i =C_sd , sd2i = T_sd, n1i= C_n, n2i =T_n , data=all.sps.treat))

write.csv(lrr.all, 'data/ms/css_all_sps_data.csv', row.names=FALSE)
```
```{r}
# plot all LRRs for each species, variable

ggplot(lrr.all, aes(variable, yi))+
  geom_errorbar(aes(ymin=yi-sei, ymax=yi+sei), width=0)+
  geom_point(aes(color=species))+
  geom_hline(yintercept=0, lty='dashed')+
  theme(axis.text.x=element_text(angle=90))

```
Create master dataframe 
```{r}
lrr.all<-read.csv('data/ms/css_all_sps_data.csv') # lrr data - needs work to combine with other species level data
lrr.sps<-lrr.all%>%dplyr::select(species,variable, yi, sei, T_mean, T_se, C_mean, C_se)%>%
  melt(id.vars=c('species','variable'), variable.name='metric')%>%
  dcast(species~variable+metric)

sps.means<-read.csv('data/ms/css_treat_means.csv') #sps means for each treatment
str(sps.means)

# sps means for all plants (complexity)...anything else?
allplants_mean<-allplants%>%
  group_by(species)%>%
  summarize(stem_mean=mean(stem_density), stem_se = se(stem_density))%>%
  left_join(lrr.sps, by='species')

write.csv(allplants_mean, 'data/ms/css_allplants_means.csv', row.names=FALSE)
str(allplants_mean)
#combine all 3, thinka bout which are important, run tests 


### plots
xvar<-allplants_mean$stem_mean
yvar<-allplants_mean$herb_omni_mg_dens_yi
ggplot(allplants_mean, aes(reorder(species, yvar), yvar))+
  geom_errorbar(aes(ymin=yvar-herb_omni_mg_dens_sei, ymax=yvar+herb_omni_mg_dens_sei), width=0, color='darkgrey', size=1.2)+
  geom_point(shape=25, size=2.5, fill='white', stroke=1)+
  geom_hline(yintercept=0, lty='dotted')+
  css_theme+
  theme(axis.text.x=element_text(angle=90, size=14, hjust=.95, vjust=.5, face='italic'))+
  labs(x='', y='Indirect defense from birds')

sp.lrr<-read.csv('data/2018/css_trait_means.csv')%>%
  left_join(allplants_mean, by='species')
str(sp.lrr)

sp.final<-sp.lrr%>%dplyr::select(species, birdfx, birdfx_se,
                       resist, resist_se, 
                       stem_mean, stem_se, 
                       iph_mg = iph_mg_omni_T_mean,iph_mg_se = iph_mg_omni_T_se,
                       iph_abun = iph_abun_omni_T_mean,iph_abun_se = iph_abun_omni_T_se,
                       lrr_iph_abun = iph_abun_omni_yi, lrr_iph_abun_se = iph_abun_omni_sei,
                       lrr_iph_mg = iph_mg_omni_yi, lrr_iph_mg_se = iph_mg_omni_sei)

plot(sp.final%>%dplyr::select(birdfx, resist, stem_mean, iph_mg, iph_abun, lrr_iph_abun, lrr_iph_mg))

write.csv(sp.final, 'data/ms/css_means_need_check.csv', row.names=FALSE)
```  

```{r}
str(allplants_mean)
plot(allplants_mean%>%
       dplyr::select(stem_mean, resist = herb_omni_mg_dens_T_mean, 
                     lrr_herb = herb_omni_mg_dens_yi, lrr_pred = pred_mg_dens_yi,
                     iph_t_mg = iph_mg_omni_T_mean, iph_c_mg = iph_mg_omni_C_mean, 
                     lrr_iph = iph_mg_omni_yi, lrr_iph_abun = iph_abun_omni_yi,
                     iph_t_abun = iph_abun_omni_T_mean, iph_c_abun = iph_abun_omni_C_mean,
                     ))


```
```{r master df}
# lrr_herb, lrr_pred, resist = herb_mg_dens, complexity, iph, lrr_iph

df<-allplants_mean%>%
       dplyr::select(sps = species, stem_mean, resist = herb_omni_mg_dens_T_mean, resist_se=herb_omni_mg_dens_T_se,
                     lrr_herb = herb_omni_mg_dens_yi, lrr_pred = pred_mg_dens_yi,
                     lrr_herb_se = herb_mg_dens_sei, lrr_pred_se = pred_mg_dens_sei, everything())%>%
  left_join(sp.list, by=c('sps'='code'))%>%
  mutate(sps_phy = gsub(' ', '_', species), lrr_herb=lrr_herb*-1, lrr_pred=lrr_pred*-1)%>%
  data.frame()
df%>%dplyr::select(sps, stem_mean, resist, lrr_herb)


```


```{r}
# PIC 
library(caper)

phy.05<-compute.brlen(phy, power=0.5) # branch length adjustment for PIC
str(df)

css.phy<-comparative.data(phy.05, df, names.col="sps_phy", na.omit=TRUE, vcv=TRUE)
#contains phylogeny, data for PIC 
```
```{r compelxity tests}

#complexity vs the world

# lrr_herb
comp_lrr_herb<-crunch(lrr_herb~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_lrr_herb #
pic.comp.lrr.herb<-caic.table(comp_lrr_herb)
caic.diagnostics(comp_lrr_herb, plot=FALSE)

# lrr_pred
comp_lrr_pred<-crunch(lrr_pred~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_lrr_pred
pic.comp.lrr.pred<-caic.table(comp_lrr_pred)
caic.diagnostics(comp_lrr_pred, plot=FALSE)

# lrr_iph_mg
comp_lrr_iph_mg<-crunch(lrr_iph_mg~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_lrr_iph_mg
pic.comp.lrr.iph.mg<-caic.table(comp_lrr_iph_mg)
caic.diagnostics(comp_lrr_iph_mg, plot=FALSE)

# lrr_iph_abun
comp_lrr_iph_abun<-crunch(lrr_iph_abun~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_lrr_iph_abun
pic.comp.lrr.iph.abun<-caic.table(comp_lrr_iph_abun)
caic.diagnostics(comp_lrr_iph_mg, plot=FALSE)

# pred_mg_dens - predator density in bird exclusion
lmmod<-lm(T_pred_mg_dens_mean~stem_mean, css.phy$data)
summary(lmmod)
comp_pred_mg_dens<-crunch(T_pred_mg_dens_mean~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_pred_mg_dens #
pic.comp.pred.mg<-caic.table(comp_pred_mg_dens)
caic.diagnostics(comp_pred_mg_dens, plot=FALSE)

ggplot(pic.comp.pred.mg, aes(stem_mean, T_pred_mg_dens_mean))+geom_point()+geom_smooth(method='lm', se=FALSE)
# predator density is related to complexity - lower with higher complexity

# herb_mg_dens - herbivore density in bird exclusion (reisst)
lmmod<-lm(resist~log(stem_mean), css.phy$data)
summary(lmmod)
shapiro.test(resid(lmmod))

comp_herb_mg_dens<-crunch(resist~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_herb_mg_dens #
pic.comp.herb.mg<-caic.table(comp_herb_mg_dens)
caic.diagnostics(comp_herb_mg_dens, plot=FALSE)
# herbivore density is NOT related to complexity - 
# so complexity increases IP, but not H  

# iph_t_mg_dens - IP:H in bird exclusion
lmmod<-lm(T_iph_abun_mean~log(stem_mean), css.phy$data)
summary(lmmod)
shapiro.test(resid(lmmod))
comp_iph_t_mg<-crunch(T_iph_abun_mean~stem_mean, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
comp_iph_t_mg
pic.comp.iph.t.mg<-caic.table(comp_iph_t_mg)
caic.diagnostics(comp_iph_t_mg, plot=FALSE)


# bird fx and reist
lmmod<-lm(lrr_herb~resist, css.phy$data)
summary(lmmod)
shapiro.test(resid(lmmod))

lrrherb_resist<-crunch(lrr_herb~resist, css.phy, stand.contr=TRUE, equal.branch.length=FALSE)
lrrherb_resist
caic.df<-caic.table(lrrherb_resist)
lmmod<-lm(lrr_herb~resist, caic.df)
summary(lmmod)


caic.diagnostics(lrrherb_resist, plot=FALSE)



```  


```{r}
sps.id<-ggplot(df, aes(reorder(species, lrr_herb), lrr_herb))+
  geom_errorbar(aes(ymin=lrr_herb-lrr_herb_se, ymax=lrr_herb+lrr_herb_se), width=0, color='darkgrey', size=1.2)+
  geom_point(shape=25, size=2.5, fill='white', stroke=1)+
  geom_hline(yintercept=0, lty='dotted')+
  css_theme+
  theme(axis.text.x=element_text(angle=90, size=14, hjust=.95, vjust=.5, face='italic'))+
  labs(x='', y='Indirect defense from birds')
sps.id


ggplot(df, aes(resist, lrr_herb))+
  geom_errorbar(aes(ymin=lrr_herb-lrr_herb_se, ymax=lrr_herb+lrr_herb_se), width=0, color='darkgrey', size=1.2)+
  geom_point(shape=25, size=2.5, fill='white', stroke=1)+
  geom_hline(yintercept=0, lty='dotted')+
  css_theme+
  theme(axis.text.x=element_text(angle=90, size=14, hjust=.95, vjust=.5, face='italic'))+
  labs(x='Direct resistance', y='Indirect defense from birds')+
  geom_smooth(method='lm', se=FALSE, color='grey40', lty='solid')+
  geom_errorbarh(aes(xmin=resist-resist_se, xmax=resist+resist_se), height=0, color='darkgrey', size=1, alpha=.7)+
  scale_x_reverse()+
  css_theme

```

Raw correlations between traits and defense  
```{r}
sp.lrr<-df
raw.cor<-rbind(tidy(cor.test(sp.lrr$lrr_herb, sp.lrr$resist))%>%mutate(yvar = 'birdfx', xvar = 'resist'),
               tidy(cor.test(sp.lrr$lrr_herb, sp.lrr$lrr_pred))%>%mutate(yvar = 'birdfx', xvar = 'hpq_log'),
               tidy(cor.test(sp.lrr$resist, sp.lrr$iph_))%>%mutate(yvar = 'resist', xvar = 'hpq_log'),
               tidy(cor.test(sp.lrr$lrr_herb, sp.lrr$complex))%>%mutate(yvar = 'birdfx', xvar = 'comp'),
               tidy(cor.test(sp.lrr$resist, sp.lrr$complex))%>%mutate(yvar = 'resist', xvar = 'comp'),
               tidy(cor.test(sp.lrr$lrr_pred, sp.lrr$complex))%>%mutate(yvar = 'lrr_pred', xvar = 'comp'),
               tidy(cor.test(sp.lrr$iph, sp.lrr$lrr_pred))%>%mutate(yvar = 'predherb', xvar = 'lrr_pred'),
               tidy(cor.test(sp.lrr$lrr_iph, sp.lrr$complex))%>%mutate(yvar = 'predherb', xvar = 'comp'))%>%
  mutate(model='raw', p.one.tail = p.value/2)

```

#### Intermediate predators : herbivores, IP:H  
```{r}
## read in data ####
sp.lrr<-read.csv('data/2018/css_trait_means.csv')%>%
  dplyr::select(T_mean,species,genus, sp_ep, contains('birdfx'), contains('resist'), contains('hpq'), contains('comp'))%>%
  mutate(herbs=T_mean, hpq_log=log(hpq+1), hpq_log_se=log(hpq_se+1), resist_log=log(resist+1), resist=resist*-1)
rownames(sp.lrr)<-sp.lrr$species

# add ratio of predators to herbivores by plant species
ph.df<-allplant%>%group_by(species, treat)%>%
  summarize(mean=mean(pred_herb, na.rm=TRUE), se=se(pred_herb))

#######################
# ratio of predators to herbivores by plant species

ggplot(ph.df, aes(treat, mean))+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1)+
  geom_point()+
  facet_wrap(~species)+
  labs(x='Treatment, C = control, T = bird exclusion', y='IP:H')

mod<-aov(pred_herb~treat, data=oplant)
summary(mod)

Anova(mod, type='III')
TukeyHSD(mod)
```
```{r}
# make species rows and cols for each ph var
ph.melt<-ph.df%>%melt(id.vars=c('species','treat'))%>%dcast(species~treat+variable)%>%
  dplyr::select(species, ph_c_mean = C_mean, ph_t_mean=T_mean, ph_c_se = C_se, ph_t_se=T_se)

sp.mean.df<-sp.lrr%>%left_join(ph.melt, by='species')

```
```{r}
## contrll vs exclusion treatment
ph.cast<-ph.df%>%dcast(species~treat, value.var='mean')
ph.cast

ggplot(ph.cast, aes(C, `T`))+
  geom_point(aes(color=species))+
  geom_smooth(method='lm', se=F, color='black')+
  geom_abline(slope=1, intercept=0, lty='dashed')+
  ylim(0,.3)+xlim(0,.3)+
  labs(y='Bird exclusion', x='Control')


lm.mod<-lm(`T`~C, data=ph.cast)
summary(lm.mod)

## is IP:H related to the bird lrr?
lm.mod<-lm(`T`~C, data=ph.cast)
summary(lm.mod)


```  


